version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: resume_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: resume_service
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: db
      DB_NAME: resume_service
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
